### Utilize o dataset zoo_2.csv e execute o algoritmo utilizando o método holdout, reservando apenas 20% dos dados para teste.
### ✦ Gere a matriz de confusão para os datasets de treino e teste.
### ✦ Compute as métricas (precision, recall e f1-score) para os conjutos de treino e teste.
### ✦ Avalie e compare os resultados obtidos pelo dataset de treino e teste e identifique se houve overfitting, underfitting ou se o modelo induzido gerado é adequado para utilizar em dados não vistos.
### ✦ Caso os resultados não estejam bons, altere os parâmetros do algoritmo para tentar melhorar o desempenho do modelo.

In [15]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
df = pd.read_csv("zoo_2.csv")
display(df)

,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,type
0,True,False,False,True,False,False,True,True,True,True,False,False,4,False,False,True,mammal
1,True,False,False,True,False,False,False,True,True,True,False,False,4,True,False,True,mammal
2,False,False,True,False,False,True,True,True,True,False,False,True,0,True,False,False,fish
3,True,False,False,True,False,False,True,True,True,True,False,False,4,False,False,True,mammal
4,True,False,False,True,False,False,True,True,True,True,False,False,4,True,False,True,mammal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,True,False,False,True,False,False,False,True,True,True,False,False,2,True,False,True,mammal
97,True,False,True,False,True,False,False,False,False,True,True,False,6,False,False,False,insect
98,True,False,False,True,False,False,True,True,True,True,False,False,4,True,False,True,mammal
99,False,False,True,False,False,False,False,False,False,True,False,False,0,False,False,False,invertebrate
100,False,True,True,False,True,False,False,False,True,True,False,False,2,True,False,False,bird

In [17]:
# Dados para treino
x = df.values[:, :16]
# Dados para teste
y = df.values[:, -1:]

In [ ]:
tree - DecisionTreeClassifier(Criterion = 'gini', random_state=42)