## Boss do Mundo 1 lvl 5
### Você foi designado para consolidar e preparar dois arquivos de dados de Pokémon para análise:
### O objetivo é unificar os dados em um único DataFrame e realizar uma série de operações de limpeza e filtragem para garantir a integridade do conjunto de dados.

## -Tarefas a serem realizadas:
### Unificar os arquivos: Combine os dados de pokedex_1.csv e pokedex_2.json em um único DataFrame, garantindo que as informações estejam corretamente alinhadas.
### Remoção de duplicatas: Verifique a existência de registros duplicados no DataFrame consolidado e elimine-os para garantir a unicidade dos dados.
### Remover colunas irrelevantes: Analise as colunas presentes e exclua aquelas que não são relevantes para a análise

## -Tarefas a serem realizadas:
### Tratar valores ausentes: Identifique valores nulos ou ausentes e aplique as ações necessárias para corrigi-los (preenchimento ou remoção).
### Filtrar Pokémon proibidos: Exclua do conjunto de dados todos os Pokémon que pertencem às seguintes categorias:
### • Lendários e Sub-lendários
### • Míticos
### • Pokémon com Mega Evoluções

In [16]:
import pandas as pd
pokedex_1 = pd.read_csv("pokedex_1.csv")
pokedex_2 = pd.read_csv("pokedex_2.csv")
pokedex_3 = pd.read_csv("pokedex_3.csv")

pokedex_1

,Unnamed: 0,pokedex_number,name,german_name,japanese_name,generation,status,species,type_number,type_1,...,against_ground,against_flying,against_psychic,against_bug,against_rock,against_ghost,against_dragon,against_dark,against_steel,against_fairy
0,0,1,Bulbasaur,Bisasam,フシギダネ (Fushigidane),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
1,1,2,Ivysaur,Bisaknosp,フシギソウ (Fushigisou),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
2,2,3,Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
3,3,3,Mega Venusaur,Bisaflor,フシギバナ (Fushigibana),1,Normal,Seed Pokémon,2,Grass,...,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5
4,4,4,Charmander,Glumanda,ヒトカゲ (Hitokage),1,Normal,Lizard Pokémon,1,Fire,...,2.0,1.0,1.0,0.5,2.0,1.0,1.0,1.0,0.5,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1040,1040,896,Glastrier,Polaross,ブリザポス (Burizaposu),8,Sub Legendary,Wild Horse Pokémon,1,Ice,...,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0
1041,1041,897,Spectrier,Phantoross,レイスポス (Reisuposu),8,Sub Legendary,Swift Horse Pokémon,1,Ghost,...,1.0,1.0,1.0,0.5,1.0,2.0,1.0,2.0,1.0,1.0
1042,1042,898,Calyrex,Coronospa,バドレックス (Budrex),8,Legendary,King Pokémon,2,Psychic,...,0.5,2.0,0.5,4.0,1.0,2.0,1.0,2.0,1.0,1.0
1043,1043,898,Calyrex Ice Rider,Coronospa,バドレックス (Budrex),8,Legendary,High King Pokémon,2,Psychic,...,1.0,1.0,0.5,2.0,2.0,2.0,1.0,2.0,2.0,1.0
1044,1044,898,Calyrex Shadow Rider,Coronospa,バドレックス (Budrex),8,Legendary,High King Pokémon,2,Psychic,...,1.0,1.0,0.5,1.0,1.0,4.0,1.0,4.0,1.0,1.0

In [17]:
# Verificando se o Dataset contem Duplicados
pokedex_1.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1040    False
1041    False
1042    False
1043    False
1044    False
Length: 1045, dtype: bool

In [18]:
pokedex_1.columns

Index(['Unnamed: 0', 'pokedex_number', 'name', 'german_name', 'japanese_name',
       'generation', 'status', 'species', 'type_number', 'type_1', 'type_2',
       'height_m', 'weight_kg', 'abilities_number', 'ability_1', 'ability_2',
       'ability_hidden', 'total_points', 'hp', 'attack', 'defense',
       'sp_attack', 'sp_defense', 'speed', 'catch_rate', 'base_friendship',
       'base_experience', 'growth_rate', 'egg_type_number', 'egg_type_1',
       'egg_type_2', 'percentage_male', 'egg_cycles', 'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fight', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy'],
      dtype='object')

In [19]:
# Removendo duplicados
# pokedex_1 = pokedex_1.drop_duplicates()
## Esta seria a funcao para remover duplicados, mas como o Dataset nao contem, nao foi necessario

In [20]:
# Removendo colunas innecessarias
pokedex_1_atualizado = pokedex_1.drop(columns=[
        'german_name', 'japanese_name', 'generation', 'type_number', 'type_1', 'type_2',
       'height_m', 'weight_kg', 'abilities_number', 'ability_1', 'ability_2',
       'ability_hidden', 'total_points', 'hp', 'attack', 'defense',
       'sp_attack', 'sp_defense', 'speed', 'catch_rate', 'base_friendship',
       'base_experience', 'growth_rate', 'egg_type_number', 'egg_type_1',
       'egg_type_2', 'percentage_male', 'egg_cycles', 'against_normal',
       'against_fire', 'against_water', 'against_electric', 'against_grass',
       'against_ice', 'against_fight', 'against_poison', 'against_ground',
       'against_flying', 'against_psychic', 'against_bug', 'against_rock',
       'against_ghost', 'against_dragon', 'against_dark', 'against_steel',
       'against_fairy'])
pokedex_1_atualizado

,Unnamed: 0,pokedex_number,name,status,species
0,0,1,Bulbasaur,Normal,Seed Pokémon
1,1,2,Ivysaur,Normal,Seed Pokémon
2,2,3,Venusaur,Normal,Seed Pokémon
3,3,3,Mega Venusaur,Normal,Seed Pokémon
4,4,4,Charmander,Normal,Lizard Pokémon
...,...,...,...,...,...
1040,1040,896,Glastrier,Sub Legendary,Wild Horse Pokémon
1041,1041,897,Spectrier,Sub Legendary,Swift Horse Pokémon
1042,1042,898,Calyrex,Legendary,King Pokémon
1043,1043,898,Calyrex Ice Rider,Legendary,High King Pokémon
1044,1044,898,Calyrex Shadow Rider,Legendary,High King Pokémon

In [21]:
## Verificando se tem valores ausentes, o DataSet não apresentou valores ausentes pois estes foram removiudos juntos com as colunas,
## mas caso o DataSet tivesse apresentado Dados nulos ou Faltantes ou ausentes, estes poderiam ter sido ou removidos, ou preenchidos ussando a função .fillna()
pokedex_1_atualizado.isnull().sum()

Unnamed: 0        0
pokedex_number    0
name              0
status            0
species           0
dtype: int64

In [22]:
#Remove todos os pokemons sub, legendarios, miticos e com mega evoluçao
pokedex_1_atualizado = pokedex_1_atualizado[
    ~pokedex_1_atualizado['status'].isin(['Sub Legendary', 'Legendary', 'Mythical']) &
    ~pokedex_1_atualizado['name'].str.contains('Mega', na=False)
]
pokedex_1_atualizado

      Unnamed: 0  pokedex_number        name  status            species
0              0               1   Bulbasaur  Normal       Seed Pokémon
1              1               2     Ivysaur  Normal       Seed Pokémon
2              2               3    Venusaur  Normal       Seed Pokémon
4              4               4  Charmander  Normal     Lizard Pokémon
5              5               5  Charmeleon  Normal      Flame Pokémon
...          ...             ...         ...     ...                ...
1023        1023             883   Arctovish  Normal     Fossil Pokémon
1024        1024             884   Duraludon  Normal      Alloy Pokémon
1025        1025             885      Dreepy  Normal  Lingering Pokémon
1026        1026             886    Drakloak  Normal  Caretaker Pokémon
1027        1027             887   Dragapult  Normal    Stealth Pokémon

[875 rows x 5 columns]